# 全局配置
server:
  port: 10000

spring:
  # 注册到eureka的服务名称
  application:
    name: file-service
  cloud:
    # 服务提供方
    consul:
      discovery:
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 注册成功后的唯一标识
        instance-id: ${spring.application.name}
        # 注册成功后的服务名称
        service-name: ${spring.application.name}
      host: 127.0.0.1
      port: 8500
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


